### ISSUE TITLE
Tiger Lake Iris XE Kext - Compilation Issues & Pre-compiled Binary Request

### ISSUE THREAD

**Issue by cemo34** [pawan295/Appleinteltgldriver.kext#5]
Hi @pawan295,

I'm trying to compile your Appleinteltgldriver.kext project on macOS 13.6.9 Build 22G830 for Tiger Lake Iris XE GPU support.

**Compilation Issues:**
- Header include path conflicts (angle brackets vs quotes)
- IOKit API deprecation warnings
- C++11 features incompatible with kernel extension compilation
- 17+ compilation errors in FakeIrisXEFramebuffer.cpp

**Questions:**
1. Is there a pre-compiled binary (.kext bundle) available?
2. Current project status? (Phase 5 mentioned as ~80% complete)
3. Specific build instructions for macOS 13.x?
4. Timeline for Phase 6+ completion?

**macOS Compatibility:**
5. Will this kext work on macOS Ventura 13.6.9?
6. Which macOS versions are supported/tested?
7. Any known compatibility issues with Ventura?

**System Info:**
- macOS: 13.6.9 Build 22G830
- Hardware: Tiger Lake CPU + Iris XE GPU (HUAWEI Matebook)
- Setup: Hackintosh (OpenCore bootloader)
- Xcode: Latest CLI tools, KDK installed

Would greatly appreciate any guidance!

Thanks!

**Comment by pawan295** [comment]
use Discussion section for normal Discussions


currently i have latest kext that works for 0x9A498086 id. see release tab for that
